AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SufixoBucket:
    Type: String
    Default: fernandosousa

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub dataops-deploy-${SufixoBucket}-${AWS::AccountId}-${AWS::Region}