name: README_CODE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  readme_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fesousa/filecode-markdown@master
        with:
          owner: fesousa
          repo: dataops-lab2
          access_token: ${{ secrets.GITHUB_TOKEN }}
          email: ${{ env.GIT_USER_EMAIL }}
          user: ${{ env.GIT_USER_NAME }}