name: Embed code in README

on:
  push:
    branches:
      - master

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - name: Markdown Embed Code From File
        uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
